package main

import "fmt"

// Satelites
var kenobi = [2]int{-500, 200}
var skywalker = [2]int{100, -100}
var sato = [2]int{500, 100}

// input: Distance to the issuer from the satellite
// output: x and y issuer coordinate
func GetLocation(distances ...float32) (x, y float32) {
	return 0.0, 0.0
}

// input: The message that is recived for each satellite
// output: The message generated by the message issuer
func GetMessage(messages ...[]string) (msg string) {
	return ""
}

func main() {
	fmt.Println("let's beging")
}
