package main

import (
	"log"

	"github.com/juancsr/quasar-attack-operation/routers"
)

// input: Distance to the issuer from the satellite
// output: x and y issuer coordinate
func GetLocation(distances ...float32) (x, y float32) {
	return 0.0, 0.0
}

// input: The message that is recived for each satellite
// output: The message generated by the message issuer
func GetMessage(messages ...[]string) (msg string) {
	return ""
}

func main() {
	log.Println("-- Launching app --")
	routers.Start()
}
