package controllers

import (
	"github.com/gin-gonic/gin"
	"github.com/juancsr/quasar-attack-operation/constants"
	"github.com/juancsr/quasar-attack-operation/models"
)

// input: Distance to the issuer from the satellite (triangulate)
// output: x and y issuer coordinate
func getLocation(distances ...float32) (x, y float32) {
	return 0.0, 0.0
}

// input: The message that is recived for each satellite
// output: The message generated by the message issuer
func getMessage(messages ...[]string) (msg string) {
	return "cool"
}

func DecriptMessage(c *gin.Context) {
	var response models.MotherShip

	distances := []float32{}
	messages := [][]string{}

	var body struct {
		Satellites []models.Satellite `json:"satellites" binding:"required"`
	}

	if c.ShouldBind(&body) != nil {
		c.AbortWithStatus(constants.NotFound_404)
	}

	for _, satellite := range body.Satellites {
		distances = append(distances, satellite.Distance)
		messages = append(messages, satellite.Message)
	}

	x, y := getLocation(distances...)
	message := getMessage(messages...)

	mothership := models.MotherShip{
		Position: models.Position{X: x, Y: y},
		Message:  message,
	}

	response = mothership

	c.JSON(constants.OK_200, response)
}
