package routers

import (
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"               // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger"           // gin-swagger middleware
	_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Quasar Attack Operation API
// @version 1.0
// @description MELI Technical Challenge
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.email juancsr@pm.me

// @license.name GNU GENERAL PUBLIC LICENSE V.30
// @license.url https://fsf.org

// @host https://quasar-attack-operation.herokuapp.com
// @BasePath /
func swagger(router *gin.Engine) {
	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))
}
